language: php
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
git:
    depth: 1
php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - phpenv config-rm xdebug.ini; fi
  - composer self-update --1
  - composer update $COMPOSER_FLAGS

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - bin/soap-server generate tests/Fixtures/Soap/config.yml soap/src/Container -vvv --dest-class=TestNs/Container/SoapServerContainer
  - php tests/example.php
